cache:
  key: "$CI_BUILD_NAME-$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - cache/

stages:
  - build
  - upload


# TER Upload when tagging in master branch
# The variables T3O_USERNAME and T3O_PASSWORD should be set in GitLab
ter-upload:
  stage: upload
  image: composer:1
  only:
    - tags
  before_script:
    - export COMPOSER_CACHE_DIR=/cache/composer
    - apk update
    - apk add  --no-cache libmcrypt  git mysql-client curl wget --virtual .build-deps freetype libxml2-dev libpng libjpeg-turbo freetype-dev libpng-dev libjpeg-turbo-dev libmcrypt-dev
    - docker-php-ext-install soap
  script:
    - composer global require namelesscoder/typo3-repository-client
    - export TYPO3_PATH_WEB="$PWD/.Build/Web"
    - >
      if [ -n "$CI_BUILD_TAG" ] && [ -n "$T3O_USERNAME" ] && [ -n "$T3O_PASSWORD" ]; then
        echo -e "Preparing upload of release ${CI_BUILD_TAG} to TER\n"
        # Cleanup before we upload
        git reset --hard HEAD && git clean -fx
        # Upload
        TAG_MESSAGE=`git tag -n10 -l $CI_BUILD_TAG | sed 's/^[0-9.]*[ ]*//g'`
        echo "Uploading release ${CI_BUILD_TAG} to TER"
        /tmp/vendor/bin/upload . "$T3O_USERNAME" "$T3O_PASSWORD" "$TAG_MESSAGE"
      fi;
